In [1]:
import pandas as pd
import nltk 
import numpy as np
import re
from nltk.stem import wordnet # to perform lemmitization
from sklearn.feature_extraction.text import CountVectorizer # to perform bow
from sklearn.feature_extraction.text import TfidfVectorizer # to perform tfidf
from nltk import pos_tag # for parts of speech
from sklearn.metrics import pairwise_distances # to perfrom cosine similarity
from nltk import word_tokenize # to create tokens
from nltk.corpus import stopwords # for stop words

In [2]:
df=pd.read_excel('dialog_talk_agent.xlsx')
df.head()

Context  \
0  Tell me about your personality   
1       I want to know you better   
2                 Define yourself   
3               Describe yourself   
4          tell me about yourself   

                                   Text Response  
0    Just think of me as the ace up your sleeve.  
1  I can help you work smarter instead of harder  
2                                            NaN  
3                                            NaN  
4                                            NaN

In [286]:
df.shape[0] # returns the number of rows in dataset

1592

In [3]:
df.ffill(axis = 0,inplace=True) # fills the null value with the previous value.
df.head(5)

Context  \
0  Tell me about your personality   
1       I want to know you better   
2                 Define yourself   
3               Describe yourself   
4          tell me about yourself   

                                   Text Response  
0    Just think of me as the ace up your sleeve.  
1  I can help you work smarter instead of harder  
2  I can help you work smarter instead of harder  
3  I can help you work smarter instead of harder  
4  I can help you work smarter instead of harder

In [4]:
df1=df.head(10) # copy of first ten rows of dataset

In [5]:
# function that converts text into lower case and removes special characters

def step1(x):
    for i in x:
        a=str(i).lower()
        p=re.sub(r'[^a-z0-9]',' ',a)
        print(p)

In [6]:
step1(df1['Context'])

tell me about your personality
i want to know you better
define yourself
describe yourself
tell me about yourself
all about you
tell me some stuff about you
talk some stuff about you
talk about yourself
about yourself


In [7]:
 # word tokenizing
    
s='tell me about your personality'
words=word_tokenize(s)
print(words)

['tell', 'me', 'about', 'your', 'personality']


In [8]:
lemma = wordnet.WordNetLemmatizer() # intializing lemmatizer
lemma.lemmatize('absorbed', pos = 'v')

'absorb'

In [9]:
pos_tag(nltk.word_tokenize(s),tagset = None) # returns the parts of speech of every word

[('tell', 'VB'),
 ('me', 'PRP'),
 ('about', 'IN'),
 ('your', 'PRP$'),
 ('personality', 'NN')]

In [308]:
# function that performs text normalization steps

def text_normalization(text):
    text=str(text).lower() # text to lower case
    spl_char_text=re.sub(r'[^ a-z]','',text) # removing special characters
    tokens=nltk.word_tokenize(spl_char_text) # word tokenizing
    lema=wordnet.WordNetLemmatizer() # intializing lemmatization
    tags_list=pos_tag(tokens,tagset=None) # parts of speech
    lema_words=[]   # empty list 
    for token,pos_token in tags_list:
        if pos_token.startswith('V'):  # Verb
            pos_val='v'
        elif pos_token.startswith('J'): # Adjective
            pos_val='a'
        elif pos_token.startswith('R'): # Adverb
            pos_val='r'
        else:
            pos_val='n' # Noun
        lema_token=lema.lemmatize(token,pos_val) # performing lemmatization
        lema_words.append(lema_token) # appending the lemmatized token into a list
    
    return " ".join(lema_words) # returns the lemmatized tokens as a sentence 

In [289]:
text_normalization('telling you some stuff about me')

'tell you some stuff about me'

In [296]:
df['lemmatized_text']=df['Context'].apply(text_normalization) # applying the fuction to the dataset to get clean text
df.head()

Context  \
0  Tell me about your personality   
1       I want to know you better   
2                 Define yourself   
3               Describe yourself   
4          tell me about yourself   

                                   Text Response  \
0    Just think of me as the ace up your sleeve.   
1  I can help you work smarter instead of harder   
2  I can help you work smarter instead of harder   
3  I can help you work smarter instead of harder   
4  I can help you work smarter instead of harder   

                  lemmatized_text  
0  tell me about your personality  
1         i want to know you good  
2                 define yourself  
3               describe yourself  
4          tell me about yourself

In [12]:
# all the stop words we have 

stop = stopwords.words('english')
print(stop)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [259]:
# bag of words

cv = CountVectorizer() # intializing the count vectorizer
X = cv.fit_transform(df['lemmatized_text']).toarray()

In [260]:
# returns all the unique word from data 

features = cv.get_feature_names()
df_bow = pd.DataFrame(X, columns = features)
df_bow.head()

abort  about  absolutely  abysmal  actually  adore  advice  advise  \
0      0      1           0        0         0      0       0       0   
1      0      0           0        0         0      0       0       0   
2      0      0           0        0         0      0       0       0   
3      0      0           0        0         0      0       0       0   
4      0      1           0        0         0      0       0       0   

   affirmative  afraid  ...  yeh  yep  yes  yet  you  your  youre  yours  \
0            0       0  ...    0    0    0    0    0     1      0      0   
1            0       0  ...    0    0    0    0    1     0      0      0   
2            0       0  ...    0    0    0    0    0     0      0      0   
3            0       0  ...    0    0    0    0    0     0      0      0   
4            0       0  ...    0    0    0    0    0     0      0      0   

   yourself  yup  
0         0    0  
1         0    0  
2         1    0  
3         1    0  
4         1    0  

[5 rows x 505 columns]

In [230]:
Question ='Will you help me and tell me about yourself more' # considering an example query

In [246]:
# checking for stop words

Q=[]
a=Question.split()
for i in a:
    if i in stop:
        continue
    else:
        Q.append(i)
    b=" ".join(Q) 

In [261]:
Question_lemma = text_normalization(b) # applying the function that we created for text normalizing
Question_bow = cv.transform([Question_lemma]).toarray() # applying bow

In [262]:
Question_bow

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [299]:
# cosine similarity for the above question we considered.

cosine_value = 1- pairwise_distances(df_bow, Question_bow, metric = 'cosine' )
(cosine_value)

array([[0.25819889],
       [0.        ],
       [0.        ],
       ...,
       [0.        ],
       [0.        ],
       [0.        ]])

In [272]:
index_value = cosine_value.argmax() # returns the index number of highest value
index_value 

194

In [302]:
(Question)

'Will you help me and tell me about yourself more'

In [301]:
df['Text Response'].loc[index_value] # The text at the above index becomes the response for the question

"I'm glad to help. What can I do for you?"

In [303]:
# using tf-idf

tfidf=TfidfVectorizer() # intializing tf-id 
x_tfidf=tfidf.fit_transform(df['lemmatized_text']).toarray() # transforming the data into array

In [304]:
# returns all the unique word from data with a score of that word

df_tfidf=pd.DataFrame(x_tfidf,columns=tfidf.get_feature_names()) 
df_tfidf.head()

abort     about  absolutely  abysmal  actually  adore  advice  advise  \
0    0.0  0.407572         0.0      0.0       0.0    0.0     0.0     0.0   
1    0.0  0.000000         0.0      0.0       0.0    0.0     0.0     0.0   
2    0.0  0.000000         0.0      0.0       0.0    0.0     0.0     0.0   
3    0.0  0.000000         0.0      0.0       0.0    0.0     0.0     0.0   
4    0.0  0.453790         0.0      0.0       0.0    0.0     0.0     0.0   

   affirmative  afraid  ...  yeh  yep  yes  yet       you      your  youre  \
0          0.0     0.0  ...  0.0  0.0  0.0  0.0  0.000000  0.330555    0.0   
1          0.0     0.0  ...  0.0  0.0  0.0  0.0  0.218768  0.000000    0.0   
2          0.0     0.0  ...  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   
3          0.0     0.0  ...  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   
4          0.0     0.0  ...  0.0  0.0  0.0  0.0  0.000000  0.000000    0.0   

   yours  yourself  yup  
0    0.0  0.000000  0.0  
1    0.0  0.000000  0.0  
2    0.0  0.641790  0.0  
3    0.0  0.641790  0.0  
4    0.0  0.608937  0.0  

[5 rows x 505 columns]

In [255]:
Question_tfidf = tfidf.transform([Question_lemma]).toarray() # applying tf-idf

In [267]:
cos=1-pairwise_distances(df_tfidf,Question_tfidf,metric='cosine')  # applying cosine similarity
cos

array([[0.40431894],
       [0.02449435],
       [0.2323051 ],
       ...,
       [0.        ],
       [0.01475171],
       [0.        ]])

In [268]:
index_value1 = cos.argmax() # returns the index number of highest value
index_value1

4

In [305]:
Question

'Will you help me and tell me about yourself more'

In [269]:
df['Text Response'].loc[index_value1]  # returns the text at that index

'I can help you work smarter instead of harder'

# Using Bag of Words

In [362]:
# Function that removes stop words and process the text

def stopword_(text):   
    tag_list=pos_tag(nltk.word_tokenize(text),tagset=None)
    stop=stopwords.words('english')
    lema=wordnet.WordNetLemmatizer()
    lema_word=[]
    for token,pos_token in tag_list:
        if token in stop:
            continue
        if pos_token.startswith('V'):
            pos_val='v'
        elif pos_token.startswith('J'):
            pos_val='a'
        elif pos_token.startswith('R'):
            pos_val='r'
        else:
            pos_val='n'
        lema_token=lema.lemmatize(token,pos_val)
        lema_word.append(lema_token)
    return " ".join(lema_word) 

In [363]:
# defining a function that returns response to query using bow

def chat_bow(text):
    s=stopword_(text)
    lemma=text_normalization(s) # calling the function to perform text normalization
    bow=cv.transform([lemma]).toarray() # applying bow
    cosine_value = 1- pairwise_distances(df_bow,bow, metric = 'cosine' )
    index_value=cosine_value.argmax() # getting index value 
    return df['Text Response'].loc[index_value]

In [364]:
chat_bow('hi there')

'Hey!'

In [366]:
chat_bow('Your are amazing')

'Terrific!'

In [367]:
chat_bow('i miss you')

"I've been right here all along!"

# Using tf-idf

In [309]:
# defining a function that returns response to query using tf-idf

def chat_tfidf(text):
    lemma=text_normalization(text) # calling the function to perform text normalization
    tf=tfidf.transform([lemma]).toarray() # applying tf-idf
    cos=1-pairwise_distances(df_tfidf,tf,metric='cosine') # applying cosine similarity
    index_value=cos.argmax() # getting index value 
    return df['Text Response'].loc[index_value]

In [324]:
chat_tfidf('hi')

'Hey!'

In [325]:
chat_tfidf('how are you')

'Lovely, thanks.'

In [315]:
chat_tfidf('i love you')

"That's great to hear."

In [316]:
chat_tfidf('thanks for your support!')

"It's my pleasure to help."

In [319]:
chat_tfidf('will you reply accurately?')

"Oh, don't give up on me!"

In [323]:
chat_tfidf('will you marry me?')

'In the virtual sense that I can, sure.'

In [359]:
chat_tfidf('i miss you and i love you')

"I've been right here all along!"

In [327]:
chat_tfidf('you are amazing and hope to see u soon.')

'Bye.'